
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aqual
 */
public class Logueo extends javax.swing.JFrame {

    /**
     * Creates new form Logueo
     */
    public Logueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Lbl_Titulo = new javax.swing.JLabel();
        Tefi_Usua = new javax.swing.JTextField();
        Pasfi_Contra = new javax.swing.JPasswordField();
        Btt_Loguear = new javax.swing.JButton();
        Lbl_Usua = new javax.swing.JLabel();
        Lbl_Contra = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Log in");
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_Titulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        Lbl_Titulo.setForeground(new java.awt.Color(204, 0, 204));
        Lbl_Titulo.setText("Inicio de sesión");
        jPanel1.add(Lbl_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 330, 50));

        Tefi_Usua.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Tefi_Usua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tefi_UsuaActionPerformed(evt);
            }
        });
        jPanel1.add(Tefi_Usua, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 290, 50));

        Pasfi_Contra.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(Pasfi_Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 290, 50));

        Btt_Loguear.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Btt_Loguear.setForeground(new java.awt.Color(51, 255, 255));
        Btt_Loguear.setText("Log in");
        Btt_Loguear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btt_LoguearMouseClicked(evt);
            }
        });
        Btt_Loguear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_LoguearActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Loguear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 50));

        Lbl_Usua.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Lbl_Usua.setForeground(new java.awt.Color(153, 153, 153));
        Lbl_Usua.setText("Usuario");
        jPanel1.add(Lbl_Usua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, 30));

        Lbl_Contra.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Lbl_Contra.setForeground(new java.awt.Color(153, 153, 153));
        Lbl_Contra.setText("Contraseña");
        jPanel1.add(Lbl_Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tefi_UsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tefi_UsuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tefi_UsuaActionPerformed

    private void Btt_LoguearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_LoguearActionPerformed
        // TODO add your handling code here:
        String Usuario = "Lesther Daniel Mendoza Tunay";
        String Carnesenia = "202010761";
        
        String UsuarioIngresado = Tefi_Usua.getText();
        String Contrasenia = Pasfi_Contra.getText();
        
        if (Usuario.equals(UsuarioIngresado)) {
            if (Carnesenia.equals(Contrasenia)) {
        JOptionPane.showMessageDialog(null, "Bienvenido " + UsuarioIngresado + 
                ", Tu carnet es: " + Carnesenia);
            }
            else {JOptionPane.showMessageDialog(null, "El usuario se encuentra registrado pero la contraseña es incorrecta.");
            }
        } else { JOptionPane.showMessageDialog(null, "No existe el usuario: " + UsuarioIngresado);
        }
        
        
    }//GEN-LAST:event_Btt_LoguearActionPerformed

    private void Btt_LoguearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_LoguearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btt_LoguearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btt_Loguear;
    private javax.swing.JLabel Lbl_Contra;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JLabel Lbl_Usua;
    private javax.swing.JPasswordField Pasfi_Contra;
    private javax.swing.JTextField Tefi_Usua;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
